"""Add models

Revision ID: 37f2c660376a
Revises: 7bada2fff2dc
Create Date: 2024-06-19 14:33:25.702059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37f2c660376a"
down_revision: Union[str, None] = "7bada2fff2dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deparment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", "job"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["deparment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employees")
    op.drop_table("job")
    op.drop_table("deparment")
    # ### end Alembic commands ###
